package auth

import (
	"path/filepath"
	"testing"
)

func TestTokenManagerGenerateValidateDelete(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "management_tokens.json")
	tm, err := NewTokenManager(filePath)
	if err != nil {
		t.Fatalf("NewTokenManager() error = %v", err)
	}

	tokenID, rawToken, err := tm.GenerateToken("admin")
	if err != nil {
		t.Fatalf("GenerateToken() error = %v", err)
	}
	if tokenID == "" || rawToken == "" {
		t.Fatalf("expected non-empty token id and token")
	}

	if !tm.ValidateToken(rawToken) {
		t.Fatalf("ValidateToken() = false, want true for generated token")
	}

	tokens := tm.ListTokens()
	if len(tokens) != 1 {
		t.Fatalf("ListTokens() len = %d, want 1", len(tokens))
	}
	if tokens[0].ID == "" {
		t.Fatalf("ListTokens() returned empty id")
	}
	if tokens[0].Hash != "" {
		t.Fatalf("ListTokens() should not expose hash")
	}

	if err := tm.DeleteToken(tokenID); err != nil {
		t.Fatalf("DeleteToken() error = %v", err)
	}
	if tm.ValidateToken(rawToken) {
		t.Fatalf("ValidateToken() = true after delete, want false")
	}
}

func TestTokenManagerValidateReloadsFromDisk(t *testing.T) {
	filePath := filepath.Join(t.TempDir(), "management_tokens.json")
	serverTM, err := NewTokenManager(filePath)
	if err != nil {
		t.Fatalf("NewTokenManager(server) error = %v", err)
	}
	cliTM, err := NewTokenManager(filePath)
	if err != nil {
		t.Fatalf("NewTokenManager(cli) error = %v", err)
	}

	tokenID, rawToken, err := cliTM.GenerateToken("admin")
	if err != nil {
		t.Fatalf("GenerateToken() error = %v", err)
	}

	if !serverTM.ValidateToken(rawToken) {
		t.Fatalf("server token manager should validate token generated by another process")
	}

	if err := cliTM.DeleteToken(tokenID); err != nil {
		t.Fatalf("DeleteToken() error = %v", err)
	}
	if serverTM.ValidateToken(rawToken) {
		t.Fatalf("server token manager should observe deleted token")
	}
}